### ISSUE TITLE
Semantic release broken

### ISSUE THREAD

**Issue by mweibel** [mweibel/lcov-result-merger#37]
https://travis-ci.org/mweibel/lcov-result-merger/jobs/350177702

```
[Semantic release]: The release type for the commit is major
[Semantic release]: Analysis of 2 commits complete: major release
[Semantic release]: The next release version is 3.0.0
[Semantic release]: Call plugin verify-release
[Semantic release]: An error occurred while running semantic-release: Error: No callback provied.
    at exports.default (/home/travis/build/mweibel/lcov-result-merger/node_modules/cracks/dist/index.js:23:11)
    at Object.verifyRelease (/home/travis/build/mweibel/lcov-result-merger/node_modules/semantic-release/lib/plugins/normalize.js:41:26)
    at run (/home/travis/build/mweibel/lcov-result-merger/node_modules/semantic-release/index.js:68:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by mweibel** [comment]
fixed
